# Generated by Django 4.0.4 on 2022-05-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESOl', 'Resolved'), ('UNRES', 'Unresolved'), ('FROZN', 'Frozen')], default='FROZN', max_length=5)),
                ('content', models.CharField(max_length=1000000, null=True)),
                ('new_message', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
